-- Juvenil · calendario 2026/27 (Juvenil Autonómica de Fútbol Sala, grupo 2).
-- Generado con:
--   python3 scripts/calendario_pdf.py Calendario.pdf --team juvenil --temporada 22 --competicion 23352276 --grupo 23382105
-- y completado a mano con lo que el script no hace:
--   1. Antes de cargarlo, la jornada 0 (partidos del senior) se fija a la liga senior, para que ffcm-sync
--      siga leyendo sus resultados cuando la competición pase a apuntar a la liga juvenil.
--   2. La jornada 0 conserva sus 4 dobles; el resto del juvenil, 1 (4 partidos por jornada en la quiniela).
--   3. Nombres cortos de los equipos de la liga juvenil.

update public.rounds r set ffcm_competicion = 22916226, ffcm_grupo = 23193707, ffcm_jornada = 1, max_doubles = 4
from public.competitions c join public.teams t on t.id = c.team_id
where r.competition_id = c.id and t.slug = 'juvenil' and r.num = 0;

update public.competitions c set max_doubles = 1, short_names = c.short_names || '{
  "F.S. LA SOLANA LA FRAGUA DE PÉREZ": "La Solana",
  "C.D. CIUDAD DE PUERTOLLANO": "Ciudad de Puertollano",
  "CLUB DEPORTIVO MEMBRILLA FUTBOL SALA": "Membrilla",
  "CONFECCIONES CARCONGA TORRENUEVA FS": "Torrenueva",
  "C.D. CARRIÓN DE CALATRAVA F.S.": "Carrión",
  "FUTSAL CORRALEÑO": "Corraleño",
  "TRT TRAILER DAIMIEL FUTBOL SALA": "Daimiel",
  "MOLINA CARPINEROS MORAL FS": "Moral",
  "TALLERES ARROYO MANZANARES FS JUVENIL": "Manzanares",
  "MIGUELTURRA F.S.": "Miguelturra"}'::jsonb
from public.teams t where t.id = c.team_id and t.slug = 'juvenil';

begin;

insert into public.competitions (team_id, name, club_name, ffcm_temporada, ffcm_competicion, ffcm_grupo)
select id, 'JUVENIL AUTONOMICA DE FÚTBOL SALA, GRUPO 2', 'CONFECCIONES CARCONGA TORRENUEVA FS', 22, 23352276, 23382105
from public.teams where slug = 'juvenil'
on conflict (team_id) do update set name = excluded.name, club_name = excluded.club_name,
  ffcm_temporada = excluded.ffcm_temporada, ffcm_competicion = excluded.ffcm_competicion, ffcm_grupo = excluded.ffcm_grupo;

insert into public.rounds (competition_id, num, match_date)
select c.id, v.num, v.d::date from public.competitions c join public.teams t on t.id = c.team_id, (values
  (1, '2026-11-07'),
  (2, '2026-11-14'),
  (3, '2026-11-21'),
  (4, '2026-11-28'),
  (5, '2026-12-12'),
  (6, '2026-12-19'),
  (7, '2027-01-16'),
  (8, '2027-01-23'),
  (9, '2027-01-30'),
  (10, '2027-02-13'),
  (11, '2027-02-20'),
  (12, '2027-02-27'),
  (13, '2027-03-06'),
  (14, '2027-03-13'),
  (15, '2027-03-20'),
  (16, '2027-04-03'),
  (17, '2027-04-17'),
  (18, '2027-04-24')
) as v(num, d) where t.slug = 'juvenil'
on conflict (competition_id, num) do update set match_date = excluded.match_date;

insert into public.fixtures (round_id, home, away)
select r.id, v.home, v.away from public.rounds r
join public.competitions c on c.id = r.competition_id join public.teams t on t.id = c.team_id, (values
  (1, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (1, 'MOLINA CARPINEROS MORAL FS', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (1, 'FUTSAL CORRALEÑO', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (1, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (1, 'MIGUELTURRA F.S.', 'C.D. CIUDAD DE PUERTOLLANO'),
  (2, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'MIGUELTURRA F.S.'),
  (2, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (2, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'MOLINA CARPINEROS MORAL FS'),
  (2, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'FUTSAL CORRALEÑO'),
  (2, 'C.D. CIUDAD DE PUERTOLLANO', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (3, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (3, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (3, 'MOLINA CARPINEROS MORAL FS', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (3, 'FUTSAL CORRALEÑO', 'C.D. CIUDAD DE PUERTOLLANO'),
  (3, 'MIGUELTURRA F.S.', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (4, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'MIGUELTURRA F.S.'),
  (4, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (4, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (4, 'C.D. CIUDAD DE PUERTOLLANO', 'MOLINA CARPINEROS MORAL FS'),
  (4, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'FUTSAL CORRALEÑO'),
  (5, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (5, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (5, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'C.D. CIUDAD DE PUERTOLLANO'),
  (5, 'MOLINA CARPINEROS MORAL FS', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (5, 'MIGUELTURRA F.S.', 'FUTSAL CORRALEÑO'),
  (6, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'MIGUELTURRA F.S.'),
  (6, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (6, 'C.D. CIUDAD DE PUERTOLLANO', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (6, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (6, 'FUTSAL CORRALEÑO', 'MOLINA CARPINEROS MORAL FS'),
  (7, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (7, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'C.D. CIUDAD DE PUERTOLLANO'),
  (7, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (7, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'FUTSAL CORRALEÑO'),
  (7, 'MIGUELTURRA F.S.', 'MOLINA CARPINEROS MORAL FS'),
  (8, 'MIGUELTURRA F.S.', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (8, 'C.D. CIUDAD DE PUERTOLLANO', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (8, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (8, 'FUTSAL CORRALEÑO', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (8, 'MOLINA CARPINEROS MORAL FS', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (9, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'C.D. CIUDAD DE PUERTOLLANO'),
  (9, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (9, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'FUTSAL CORRALEÑO'),
  (9, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'MOLINA CARPINEROS MORAL FS'),
  (9, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'MIGUELTURRA F.S.'),
  (10, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (10, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'MOLINA CARPINEROS MORAL FS'),
  (10, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'FUTSAL CORRALEÑO'),
  (10, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (10, 'C.D. CIUDAD DE PUERTOLLANO', 'MIGUELTURRA F.S.'),
  (11, 'MIGUELTURRA F.S.', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (11, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (11, 'MOLINA CARPINEROS MORAL FS', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (11, 'FUTSAL CORRALEÑO', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (11, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'C.D. CIUDAD DE PUERTOLLANO'),
  (12, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (12, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (12, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'MOLINA CARPINEROS MORAL FS'),
  (12, 'C.D. CIUDAD DE PUERTOLLANO', 'FUTSAL CORRALEÑO'),
  (12, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'MIGUELTURRA F.S.'),
  (13, 'MIGUELTURRA F.S.', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (13, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (13, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (13, 'MOLINA CARPINEROS MORAL FS', 'C.D. CIUDAD DE PUERTOLLANO'),
  (13, 'FUTSAL CORRALEÑO', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (14, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (14, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (14, 'C.D. CIUDAD DE PUERTOLLANO', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (14, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'MOLINA CARPINEROS MORAL FS'),
  (14, 'FUTSAL CORRALEÑO', 'MIGUELTURRA F.S.'),
  (15, 'MIGUELTURRA F.S.', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (15, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (15, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'C.D. CIUDAD DE PUERTOLLANO'),
  (15, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (15, 'MOLINA CARPINEROS MORAL FS', 'FUTSAL CORRALEÑO'),
  (16, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (16, 'C.D. CIUDAD DE PUERTOLLANO', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (16, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (16, 'FUTSAL CORRALEÑO', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ'),
  (16, 'MOLINA CARPINEROS MORAL FS', 'MIGUELTURRA F.S.'),
  (17, 'TALLERES ARROYO MANZANARES FS JUVENIL', 'MIGUELTURRA F.S.'),
  (17, 'TRT TRAILER DAIMIEL FUTBOL SALA', 'C.D. CIUDAD DE PUERTOLLANO'),
  (17, 'C.D. CARRIÓN DE CALATRAVA F.S.', 'CONFECCIONES CARCONGA TORRENUEVA FS'),
  (17, 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA', 'FUTSAL CORRALEÑO'),
  (17, 'F.S. LA SOLANA LA FRAGUA DE PÉREZ', 'MOLINA CARPINEROS MORAL FS'),
  (18, 'C.D. CIUDAD DE PUERTOLLANO', 'TALLERES ARROYO MANZANARES FS JUVENIL'),
  (18, 'CONFECCIONES CARCONGA TORRENUEVA FS', 'TRT TRAILER DAIMIEL FUTBOL SALA'),
  (18, 'FUTSAL CORRALEÑO', 'C.D. CARRIÓN DE CALATRAVA F.S.'),
  (18, 'MOLINA CARPINEROS MORAL FS', 'CLUB DEPORTIVO MEMBRILLA FUTBOL SALA'),
  (18, 'MIGUELTURRA F.S.', 'F.S. LA SOLANA LA FRAGUA DE PÉREZ')
) as v(num, home, away) where t.slug = 'juvenil' and r.num = v.num
on conflict (round_id, home, away) do nothing;

commit;
